USE bhim2208_AB


GO
CREATE OR ALTER TRIGGER tr_Focistak_Delete
ON Focistak
INSTEAD OF DELETE
AS
BEGIN
	SET NOCOUNT ON

	DELETE FROM Megkap 
	WHERE FID IN (SELECT FID FROM deleted)

	DELETE FROM Jatszik
	WHERE FID IN (SELECT FID FROM deleted)

	DELETE FROM Atigazolasok
	WHERE AID IN (SELECT AID FROM AtigazoltFocistak WHERE FID IN (SELECT FID FROM deleted))

	DELETE FROM AtigazoltFocistak
	WHERE FID IN (SELECT FID FROM deleted)

	DELETE FROM Focistak
	WHERE FID IN (SELECT FID FROM deleted) 
END
GO